services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - 'POSTGRES_DB=ads_dental_surgeries_db'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=koffi'
    ports:
      - '5432:5432'
#    networks:
#      - dentalSurgeries-net

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: koffiah.tipoh@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - '5050:5050'

#  app:
#    image: 'ads-dental-surgeries'
#    build:
#      context: .
#    container_name: app
#    ports:
#      - '8080:8080'
##    networks:
##      - dentalSurgeries-net
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ads_dental_surgeries_db
#      - SPRING_DATASOURCE_USERNAME=koffi
#      - SPRING_DATASOURCE_PASSWORD=1234
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=create

#  networks:
#    dentalSurgeries-net